"""
tests/integration/test_pipeline_minimal.py
===========================================
Minimal integration test for the PPTX → video pipeline.

Does NOT require:
  - Network access (TTS is mocked with a silent WAV generated by ffmpeg)
  - A real PPTX with slide images (LibreOffice / COM) — skipped if unavailable

Requires (must be on PATH):
  - ffmpeg / ffprobe

Run with:
    pytest tests/integration/test_pipeline_minimal.py -v
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Bootstrap: add scripts dir to sys.path so imports resolve without install
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SCRIPTS_DIR = REPO_ROOT / "services" / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from ffmpeg_helpers import (  # noqa: E402
    concat_videos,
    create_slide_video,
    generate_srt,
    get_audio_duration,
    trim_trailing_silence,
)

FIXTURES_DIR = Path(__file__).parent.parent / "fixtures"
SAMPLE_PPTX  = FIXTURES_DIR / "sample.pptx"
TMP          = Path(__file__).parent / "_tmp_pipeline_test"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _check_ffmpeg() -> bool:
    try:
        subprocess.run(["ffmpeg", "-version"], capture_output=True, check=True)
        return True
    except (FileNotFoundError, subprocess.CalledProcessError):
        return False


def _make_silent_wav(path: Path, duration_sec: float = 2.0) -> Path:
    """Generate a silent WAV file using ffmpeg (no network needed)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi",
            "-i", f"anullsrc=r=44100:cl=mono",
            "-t", str(duration_sec),
            "-c:a", "pcm_s16le",
            str(path),
        ],
        capture_output=True,
        check=True,
    )
    return path


def _make_tone_then_silence(path: Path, tone_sec: float = 1.0, silence_sec: float = 2.0) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi", "-i", f"sine=frequency=880:duration={tone_sec}",
            "-f", "lavfi", "-i", f"anullsrc=r=44100:cl=mono:d={silence_sec}",
            "-filter_complex", "[0:a][1:a]concat=n=2:v=0:a=1[outa]",
            "-map", "[outa]",
            str(path),
        ],
        capture_output=True,
        check=True,
    )
    return path


def _make_blank_png(path: Path, w: int = 640, h: int = 360) -> Path:
    """Generate a blank black PNG using ffmpeg (no PIL needed)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi",
            "-i", f"color=c=black:s={w}x{h}:r=1",
            "-frames:v", "1",
            str(path),
        ],
        capture_output=True,
        check=True,
    )
    return path


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module", autouse=True)
def workspace(tmp_path_factory):
    """Create a per-test-module temp directory."""
    d = tmp_path_factory.mktemp("pipeline")
    return d


@pytest.fixture(scope="module")
def sample_image(workspace):
    return _make_blank_png(workspace / "slide_01.png")


@pytest.fixture(scope="module")
def sample_audio(workspace):
    return _make_silent_wav(workspace / "audio_01.wav", duration_sec=2.5)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

pytestmark = pytest.mark.skipif(
    not _check_ffmpeg(),
    reason="ffmpeg not found on PATH — skipping pipeline tests",
)


class TestAudioDuration:
    def test_silent_wav_duration(self, workspace, sample_audio):
        dur = get_audio_duration(str(sample_audio))
        assert 2.0 <= dur <= 3.0, f"Unexpected duration: {dur}"


class TestCreateSlideVideo:
    def test_creates_mp4(self, workspace, sample_image, sample_audio):
        out = workspace / "parts" / "part_01.mp4"
        result = create_slide_video(
            str(sample_image),
            str(sample_audio),
            str(out),
            resolution=(640, 360),
        )
        assert Path(result).exists()
        assert Path(result).stat().st_size > 0

    def test_duration_close_to_audio(self, workspace, sample_image, sample_audio):
        out = workspace / "parts" / "part_01b.mp4"
        create_slide_video(str(sample_image), str(sample_audio), str(out), resolution=(640, 360))
        dur = get_audio_duration(str(out))
        # Should be within 0.5 s of the audio
        assert abs(dur - 2.5) < 0.5, f"Video duration {dur}s far from audio 2.5s"

    def test_duration_can_include_short_slide_hold(self, workspace, sample_image, sample_audio):
        out = workspace / "parts" / "part_01c.mp4"
        create_slide_video(
            str(sample_image),
            str(sample_audio),
            str(out),
            resolution=(640, 360),
            duration_sec=2.8,
        )
        dur = get_audio_duration(str(out))
        assert abs(dur - 2.8) < 0.35, f"Video duration {dur}s far from requested 2.8s"


class TestAudioSyncCleanup:
    def test_trim_trailing_silence_reduces_dead_air(self, workspace):
        audio = _make_tone_then_silence(workspace / "tone_then_silence.wav", tone_sec=1.0, silence_sec=2.0)
        before = get_audio_duration(str(audio))
        trim_trailing_silence(str(audio))
        after = get_audio_duration(str(audio))

        assert before > 2.5
        assert after < before - 1.0
        assert 0.5 <= after <= 1.6


class TestConcatVideos:
    def test_concat_two_clips(self, workspace, sample_image, sample_audio):
        parts_dir = workspace / "concat_parts"

        # Create two small clips
        clips = []
        for i in range(1, 3):
            audio = _make_silent_wav(parts_dir / f"a{i}.wav", duration_sec=1.0)
            img   = _make_blank_png(parts_dir / f"s{i}.png", 640, 360)
            clip  = str(parts_dir / f"clip_{i}.mp4")
            create_slide_video(str(img), str(audio), clip, resolution=(640, 360))
            clips.append(clip)

        out = str(workspace / "final" / "lesson.mp4")
        result = concat_videos(clips, out)

        assert Path(result).exists()
        # Combined duration should be ≈ 2 s
        dur = get_audio_duration(str(result))
        assert 1.5 <= dur <= 3.0, f"Concatenated duration {dur}s out of expected range"


class TestGenerateSrt:
    def test_srt_file_created(self, workspace):
        srt_path = str(workspace / "lesson.srt")
        result = generate_srt(
            ["Hello world", "This is slide two"],
            [3.0, 4.5],
            srt_path,
        )
        content = Path(result).read_text(encoding="utf-8")
        assert "00:00:00,000 --> 00:00:03,000" in content
        assert "00:00:03,000 --> 00:00:07,500" in content
        assert "Hello world" in content
        assert "This is slide two" in content

    def test_mismatched_lengths_raise(self, workspace):
        with pytest.raises(ValueError, match="equal length"):
            generate_srt(["A"], [1.0, 2.0], str(workspace / "bad.srt"))


class TestExtractNotes:
    """Tests against sample.pptx fixture — skipped if fixture missing."""

    @pytest.mark.skipif(
        not SAMPLE_PPTX.exists(),
        reason="tests/fixtures/sample.pptx not found",
    )
    def test_extract_notes_from_sample(self, workspace):
        sys.path.insert(0, str(SCRIPTS_DIR))
        from pptx_extract import extract_speaker_notes

        notes_dir = str(workspace / "notes")
        note_paths = extract_speaker_notes(str(SAMPLE_PPTX), notes_dir)
        assert len(note_paths) > 0
        for p in note_paths:
            assert Path(p).exists()
