# Generated by Django 4.2.29 on 2026-05-02 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_project_last_moderation_run_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(max_length=50)),
                ('modality', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('is_blocking', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=50)),
                ('phase', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=30)),
                ('final_decision', models.CharField(blank=True, max_length=30)),
                ('policy_version', models.CharField(default='moderation:v1', max_length=50)),
                ('input_hash', models.CharField(blank=True, max_length=64)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='core.project')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_agent_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_slug', models.CharField(max_length=100)),
                ('agent_version', models.CharField(max_length=50)),
                ('content_type', models.CharField(max_length=50)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(max_length=80)),
                ('severity', models.CharField(max_length=30)),
                ('confidence', models.FloatField(default=0.0)),
                ('decision', models.CharField(max_length=30)),
                ('user_message', models.TextField(blank=True)),
                ('admin_message', models.TextField(blank=True)),
                ('evidence_excerpt', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('provider_raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='ai_agents.agentrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='open', max_length=30)),
                ('publisher_message', models.TextField(blank=True)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_review_requests', to='core.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_review_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_reviews_done', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_review_requests', to='ai_agents.agentrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationBlockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_by', models.CharField(max_length=100)),
                ('reason_category', models.CharField(max_length=80)),
                ('highest_severity', models.CharField(max_length=30)),
                ('message_to_user', models.TextField()),
                ('message_to_admin', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_blocks', to='core.project')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_publication_blocks', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_block_events', to='ai_agents.agentrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'resolved'], name='ai_agents_p_project_a840a4_idx'), models.Index(fields=['reason_category', 'highest_severity'], name='ai_agents_p_reason__3ea896_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['project', 'purpose', 'status'], name='ai_agents_a_project_54c15e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['phase', 'status'], name='ai_agents_a_phase_ae8115_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinding',
            index=models.Index(fields=['run', 'decision'], name='ai_agents_a_run_id_550691_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinding',
            index=models.Index(fields=['category', 'severity'], name='ai_agents_a_categor_0ca976_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfinding',
            index=models.Index(fields=['content_type', 'object_type'], name='ai_agents_a_content_80391a_idx'),
        ),
        migrations.AddIndex(
            model_name='adminreviewrequest',
            index=models.Index(fields=['project', 'status'], name='ai_agents_a_project_5f0ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='adminreviewrequest',
            index=models.Index(fields=['requested_by', 'status'], name='ai_agents_a_request_7dea09_idx'),
        ),
    ]
