const STUDIO_WORKSPACE_MESSAGES = {
  en: {
    slides: 'Slides',
    slidesHint: 'Select a slide to edit',
    slideCount: 'slides',
    loadingSlides: 'Loading slides',
    noSlides: 'No slides yet',
    noSlidesHint: 'Upload a source file to create the first slide.',
    slide: 'Slide',
    slideActions: 'Slide actions',
    selectSlide: 'Select slide',
    moveUp: 'Move up',
    moveDown: 'Move down',
    duplicate: 'Duplicate',
    duplicateUnavailable: 'Duplicate is not supported by the current transcript API.',
    delete: 'Delete',
    copy: 'Copy',
    paste: 'Paste',
    pasteUnavailable: 'Paste is unavailable for this slide.',
    rename: 'Rename',
    renameUnavailable: 'Rename is not supported by the current transcript API.',
    dragToReorder: 'Drag to reorder',
    renderStatus: 'Render status',
    renderReady: 'Ready',
    renderProcessing: 'Processing',
    renderQueued: 'Queued',
    renderFailed: 'Failed',
    renderDraft: 'Not rendered',
    renderIdleHint: 'Render activity will appear here.',
    renderActiveHint: 'You can keep editing while this render continues.',
    renderReadyHint: 'The latest video is ready to preview.',
    renderFailedHint: 'Review the error and try rendering again.',
    inspector: 'Inspector',
    inspectorHint: 'Controls for the selected slide',
    moreActions: 'More actions',
    saving: 'Saving...',
    saved: 'Saved',
    unsavedChanges: 'Unsaved changes',
    upToDate: 'Up to date',
    lastSaved: 'Last saved',
    neverSaved: 'Not saved yet',
    noProjectTitle: 'No project selected',
    noProjectHint: 'Select a project or create a lesson draft to begin editing.',
    noSlideTitle: 'No slide selected',
    noSlideHint: 'Choose a slide from the filmstrip to edit its scene settings.',
    noAssetsTitle: 'No assets',
    noAssetsHint: 'Upload a source file, cover, or slide background to add assets.',
    noAvatarTitle: 'No avatar',
    noAvatarHint: 'Avatar rendering is not enabled for this lesson.',
    noNarrationTitle: 'No narration',
    noNarrationHint: 'Add transcript text before rendering narration.',
    creatorEyebrow: 'AI creator workspace',
    creatorUntitledLesson: 'Untitled lesson',
    creatorNewLessonDraft: 'New lesson draft',
    creatorDescriptionFallback: 'Shape the script, scene, render, and release path from one creator workspace.',
    creatorMetadataLabel: 'Creator metadata',
    creatorSummaryLabel: 'Creator summary',
    creatorNextBestAction: 'Next best action',
    creatorContinueEditing: 'Continue editing',
    creatorStatusPublished: 'Published',
    creatorStatusRendering: 'Rendering',
    creatorStatusReady: 'Ready',
    creatorStatusDraft: 'Draft',
    creatorAiReady: 'AI Ready',
    creatorPublishReady: 'Publish Ready',
    creatorNeedsAttention: 'Needs Attention',
    creatorAvatarLabel: 'Avatar',
    creatorVoiceLabel: 'Voice',
    creatorLanguageLabel: 'Language',
    creatorDurationLabel: 'Duration',
    creatorAutoVoice: 'Auto voice',
    creatorAvatarDisabled: 'Avatar disabled.',
    creatorAvatarProcessing: 'Avatar processing...',
    creatorAvatarFailed: 'Avatar failed. Base video is still published.',
    creatorAvatarMotionFallback: 'Avatar lip-sync completed; motion fallback was used.',
    creatorAvatarStaticFallback: 'Avatar used static fallback because motion stage failed.',
    creatorAvatarMotionReady: 'Avatar ready with motion.',
    creatorAvatarReady: 'Avatar ready.',
    creatorCreateThisLesson: 'Create this lesson',
    creatorAddSourceFile: 'Add a source file',
    creatorResolveBlocker: 'Resolve the blocker',
    creatorRenderUpdatedVideo: 'Render the updated video',
    creatorSaveCurrentEdits: 'Save current edits',
    creatorPublishReadyLesson: 'Publish the ready lesson',
    creatorWatchPublishedLesson: 'Watch the published lesson',
    creatorPreviewDraft: 'Preview the draft',
    creatorDetailCreateLesson: 'Use the draft controls to create a lesson from the selected source.',
    creatorDetailRenderUpdated: 'The transcript, slide, or voice changes require a fresh render before publishing.',
    creatorDetailSaveChanges: 'Save draft changes before rendering or publishing.',
    creatorDetailPublishReady: 'Rendering and moderation are ready for release.',
    creatorDetailWatchPublished: 'The public lesson is live and ready to review in Watch.',
    creatorDetailPreviewDraft: 'A rendered draft is available for owner preview.',
    creatorDetailContinueEditing: 'Work in the canvas until the lesson is ready to render.',
    creatorCreating: 'Creating...',
    creatorCreateLesson: 'Create Lesson',
    creatorSaveLocalDraft: 'Save Local Draft',
    creatorRender: 'Render',
    creatorRenderRerenderTitle: 'Save changes and queue a video rerender.',
    creatorSaveChanges: 'Save changes',
    creatorPublish: 'Publish',
    creatorWatch: 'Watch',
    creatorPreviewInWatch: 'Preview In Watch',
  },
  tr: {
    slides: 'Slaytlar',
    slidesHint: 'Düzenlemek için bir slayt seçin',
    loadingSlides: 'Slaytlar yükleniyor',
    noSlides: 'Henüz slayt yok',
    noSlidesHint: 'İlk slaytı oluşturmak için bir kaynak dosya yükleyin.',
    slide: 'Slayt',
    renderStatus: 'Render durumu',
    renderReady: 'Hazır',
    renderProcessing: 'İşleniyor',
    renderQueued: 'Sırada',
    renderFailed: 'Başarısız',
    renderDraft: 'Render edilmedi',
    renderIdleHint: 'Render etkinliği burada görünecek.',
    renderActiveHint: 'Render devam ederken düzenlemeye devam edebilirsiniz.',
    renderReadyHint: 'En son video önizlemeye hazır.',
    renderFailedHint: 'Hatayı inceleyip yeniden render etmeyi deneyin.',
    inspector: 'Denetleyici',
    inspectorHint: 'Seçili slaytın kontrolleri',
    moreActions: 'Diğer işlemler',
    saving: 'Kaydediliyor...',
    saved: 'Kaydedildi',
    unsavedChanges: 'Kaydedilmemiş değişiklikler',
    upToDate: 'Güncel',
    lastSaved: 'Son kayıt',
    neverSaved: 'Henüz kaydedilmedi',
    creatorEyebrow: 'Yapay zeka üretim alanı',
    creatorUntitledLesson: 'Adsız ders',
    creatorNewLessonDraft: 'Yeni ders taslağı',
    creatorDescriptionFallback: 'Metni, sahneyi, render ve yayın akışını tek üretim alanından yönetin.',
    creatorMetadataLabel: 'Üretici metadatası',
    creatorSummaryLabel: 'Üretici özeti',
    creatorNextBestAction: 'Sonraki en iyi adım',
    creatorContinueEditing: 'Düzenlemeye devam et',
    creatorStatusPublished: 'Yayında',
    creatorStatusRendering: 'Render alınıyor',
    creatorStatusReady: 'Hazır',
    creatorStatusDraft: 'Taslak',
    creatorAiReady: 'Yapay zeka hazır',
    creatorPublishReady: 'Yayına hazır',
    creatorNeedsAttention: 'İlgi gerekiyor',
    creatorAvatarLabel: 'Avatar',
    creatorVoiceLabel: 'Ses',
    creatorLanguageLabel: 'Dil',
    creatorDurationLabel: 'Süre',
    creatorAutoVoice: 'Otomatik ses',
    creatorAvatarDisabled: 'Avatar devre dışı.',
    creatorAvatarProcessing: 'Avatar işleniyor...',
    creatorAvatarFailed: 'Avatar başarısız oldu. Temel video yayında kalır.',
    creatorAvatarMotionFallback: 'Avatar dudak senkronu tamamlandı; hareket yedeği kullanıldı.',
    creatorAvatarStaticFallback: 'Hareket aşaması başarısız olduğu için statik avatar yedeği kullanıldı.',
    creatorAvatarMotionReady: 'Avatar hareketli olarak hazır.',
    creatorAvatarReady: 'Avatar hazır.',
    creatorCreateThisLesson: 'Bu dersi oluştur',
    creatorAddSourceFile: 'Kaynak dosya ekle',
    creatorResolveBlocker: 'Engeli çöz',
    creatorRenderUpdatedVideo: 'Güncel videoyu render et',
    creatorSaveCurrentEdits: 'Düzenlemeleri kaydet',
    creatorPublishReadyLesson: 'Hazır dersi yayınla',
    creatorWatchPublishedLesson: 'Yayındaki dersi izle',
    creatorPreviewDraft: 'Taslağı önizle',
    creatorDetailCreateLesson: 'Seçili kaynaktan ders oluşturmak için taslak kontrollerini kullanın.',
    creatorDetailRenderUpdated: 'Metin, slayt veya ses değişiklikleri yayın öncesi yeni render gerektirir.',
    creatorDetailSaveChanges: 'Render veya yayından önce taslak değişikliklerini kaydedin.',
    creatorDetailPublishReady: 'Render ve moderasyon yayın için hazır.',
    creatorDetailWatchPublished: 'Herkese açık ders yayında ve Watch içinde incelemeye hazır.',
    creatorDetailPreviewDraft: 'Render edilmiş taslak sahip önizlemesi için hazır.',
    creatorDetailContinueEditing: 'Ders render için hazır olana kadar tuvalde çalışın.',
    creatorCreating: 'Oluşturuluyor...',
    creatorCreateLesson: 'Ders Oluştur',
    creatorSaveLocalDraft: 'Yerel Taslağı Kaydet',
    creatorRender: 'Render',
    creatorRenderRerenderTitle: 'Değişiklikleri kaydedip video renderını sıraya alın.',
    creatorSaveChanges: 'Değişiklikleri kaydet',
    creatorPublish: 'Yayınla',
    creatorWatch: 'İzle',
    creatorPreviewInWatch: 'Watch içinde önizle',
  },
  es: {
    renderStatus: 'Estado de renderizado',
    renderReady: 'Listo',
    renderProcessing: 'Procesando',
    renderQueued: 'En cola',
    renderFailed: 'Error',
    renderDraft: 'Sin renderizar',
    renderIdleHint: 'La actividad de renderizado aparecerá aquí.',
    renderActiveHint: 'Puedes seguir editando mientras continúa este renderizado.',
    renderReadyHint: 'El video más reciente está listo para previsualizar.',
    renderFailedHint: 'Revisa el error e intenta renderizar de nuevo.',
    saving: 'Guardando...',
    lastSaved: 'Último guardado',
    creatorEyebrow: 'Espacio de creación con IA',
    creatorUntitledLesson: 'Lección sin título',
    creatorNewLessonDraft: 'Nuevo borrador de lección',
    creatorDescriptionFallback: 'Da forma al guion, la escena, el renderizado y la publicación desde un solo espacio de creación.',
    creatorMetadataLabel: 'Metadatos del creador',
    creatorSummaryLabel: 'Resumen del creador',
    creatorNextBestAction: 'Siguiente mejor acción',
    creatorContinueEditing: 'Seguir editando',
    creatorStatusPublished: 'Publicado',
    creatorStatusRendering: 'Renderizando',
    creatorStatusReady: 'Listo',
    creatorStatusDraft: 'Borrador',
    creatorAiReady: 'IA lista',
    creatorPublishReady: 'Listo para publicar',
    creatorNeedsAttention: 'Requiere atención',
    creatorAvatarLabel: 'Avatar',
    creatorVoiceLabel: 'Voz',
    creatorLanguageLabel: 'Idioma',
    creatorDurationLabel: 'Duración',
    creatorAutoVoice: 'Voz automática',
    creatorAvatarDisabled: 'Avatar desactivado.',
    creatorAvatarProcessing: 'Procesando avatar...',
    creatorAvatarFailed: 'El avatar falló. El video base sigue publicado.',
    creatorAvatarMotionFallback: 'Sincronización labial completada; se usó movimiento de respaldo.',
    creatorAvatarStaticFallback: 'Se usó avatar estático porque falló la etapa de movimiento.',
    creatorAvatarMotionReady: 'Avatar listo con movimiento.',
    creatorAvatarReady: 'Avatar listo.',
    creatorCreateThisLesson: 'Crear esta lección',
    creatorAddSourceFile: 'Agregar archivo fuente',
    creatorResolveBlocker: 'Resolver el bloqueo',
    creatorRenderUpdatedVideo: 'Renderizar el video actualizado',
    creatorSaveCurrentEdits: 'Guardar cambios actuales',
    creatorPublishReadyLesson: 'Publicar la lección lista',
    creatorWatchPublishedLesson: 'Ver la lección publicada',
    creatorPreviewDraft: 'Previsualizar borrador',
    creatorDetailCreateLesson: 'Usa los controles del borrador para crear una lección desde la fuente seleccionada.',
    creatorDetailRenderUpdated: 'Los cambios de guion, diapositiva o voz requieren un nuevo render antes de publicar.',
    creatorDetailSaveChanges: 'Guarda los cambios del borrador antes de renderizar o publicar.',
    creatorDetailPublishReady: 'Renderizado y moderación están listos para publicar.',
    creatorDetailWatchPublished: 'La lección pública está activa y lista para revisar en Watch.',
    creatorDetailPreviewDraft: 'Hay un borrador renderizado listo para la vista previa del propietario.',
    creatorDetailContinueEditing: 'Trabaja en el lienzo hasta que la lección esté lista para renderizar.',
    creatorCreating: 'Creando...',
    creatorCreateLesson: 'Crear lección',
    creatorSaveLocalDraft: 'Guardar borrador local',
    creatorRender: 'Renderizar',
    creatorRenderRerenderTitle: 'Guarda los cambios y pon en cola un nuevo render de video.',
    creatorSaveChanges: 'Guardar cambios',
    creatorPublish: 'Publicar',
    creatorWatch: 'Ver',
    creatorPreviewInWatch: 'Previsualizar en Watch',
  },
  fr: {
    renderStatus: 'Statut du rendu',
    renderReady: 'Prêt',
    renderProcessing: 'Traitement',
    renderQueued: 'En file',
    renderFailed: 'Échec',
    renderDraft: 'Non rendu',
    renderIdleHint: "L'activité de rendu s'affichera ici.",
    renderActiveHint: 'Vous pouvez continuer à modifier pendant ce rendu.',
    renderReadyHint: 'La dernière vidéo est prête à prévisualiser.',
    renderFailedHint: "Vérifiez l'erreur puis relancez le rendu.",
    saving: 'Enregistrement...',
    lastSaved: 'Dernier enregistrement',
    creatorEyebrow: 'Espace de création IA',
    creatorUntitledLesson: 'Leçon sans titre',
    creatorNewLessonDraft: 'Nouveau brouillon de leçon',
    creatorDescriptionFallback: 'Travaillez le script, la scène, le rendu et la publication depuis un seul espace de création.',
    creatorMetadataLabel: 'Métadonnées du créateur',
    creatorSummaryLabel: 'Résumé du créateur',
    creatorNextBestAction: 'Meilleure action suivante',
    creatorContinueEditing: 'Continuer la modification',
    creatorStatusPublished: 'Publié',
    creatorStatusRendering: 'Rendu en cours',
    creatorStatusReady: 'Prêt',
    creatorStatusDraft: 'Brouillon',
    creatorAiReady: 'IA prête',
    creatorPublishReady: 'Prêt à publier',
    creatorNeedsAttention: 'À vérifier',
    creatorAvatarLabel: 'Avatar',
    creatorVoiceLabel: 'Voix',
    creatorLanguageLabel: 'Langue',
    creatorDurationLabel: 'Durée',
    creatorAutoVoice: 'Voix automatique',
    creatorAvatarDisabled: 'Avatar désactivé.',
    creatorAvatarProcessing: "Traitement de l'avatar...",
    creatorAvatarFailed: "L'avatar a échoué. La vidéo de base reste publiée.",
    creatorAvatarMotionFallback: "Synchronisation labiale terminée; mouvement de secours utilisé.",
    creatorAvatarStaticFallback: "Avatar statique utilisé car l'étape de mouvement a échoué.",
    creatorAvatarMotionReady: 'Avatar prêt avec mouvement.',
    creatorAvatarReady: 'Avatar prêt.',
    creatorCreateThisLesson: 'Créer cette leçon',
    creatorAddSourceFile: 'Ajouter un fichier source',
    creatorResolveBlocker: 'Résoudre le blocage',
    creatorRenderUpdatedVideo: 'Rendre la vidéo mise à jour',
    creatorSaveCurrentEdits: 'Enregistrer les modifications',
    creatorPublishReadyLesson: 'Publier la leçon prête',
    creatorWatchPublishedLesson: 'Regarder la leçon publiée',
    creatorPreviewDraft: 'Prévisualiser le brouillon',
    creatorDetailCreateLesson: 'Utilisez les contrôles du brouillon pour créer une leçon depuis la source sélectionnée.',
    creatorDetailRenderUpdated: 'Les changements de script, de diapositive ou de voix nécessitent un nouveau rendu avant publication.',
    creatorDetailSaveChanges: 'Enregistrez le brouillon avant le rendu ou la publication.',
    creatorDetailPublishReady: 'Le rendu et la modération sont prêts pour la publication.',
    creatorDetailWatchPublished: 'La leçon publique est en ligne et prête à être vérifiée dans Watch.',
    creatorDetailPreviewDraft: 'Un brouillon rendu est disponible pour la prévisualisation propriétaire.',
    creatorDetailContinueEditing: "Travaillez dans le canevas jusqu'à ce que la leçon soit prête pour le rendu.",
    creatorCreating: 'Création...',
    creatorCreateLesson: 'Créer la leçon',
    creatorSaveLocalDraft: 'Enregistrer le brouillon local',
    creatorRender: 'Rendre',
    creatorRenderRerenderTitle: 'Enregistrez les changements et mettez un nouveau rendu vidéo en file.',
    creatorSaveChanges: 'Enregistrer',
    creatorPublish: 'Publier',
    creatorWatch: 'Regarder',
    creatorPreviewInWatch: 'Prévisualiser dans Watch',
  },
  de: {
    renderStatus: 'Renderstatus',
    renderReady: 'Bereit',
    renderProcessing: 'Wird verarbeitet',
    renderQueued: 'In Warteschlange',
    renderFailed: 'Fehlgeschlagen',
    renderDraft: 'Nicht gerendert',
    renderIdleHint: 'Renderaktivität erscheint hier.',
    renderActiveHint: 'Du kannst weiter bearbeiten, während dieses Rendering läuft.',
    renderReadyHint: 'Das neueste Video ist bereit zur Vorschau.',
    renderFailedHint: 'Prüfe den Fehler und rendere erneut.',
    saving: 'Speichern...',
    lastSaved: 'Zuletzt gespeichert',
    creatorEyebrow: 'KI-Creator-Arbeitsbereich',
    creatorUntitledLesson: 'Unbenannte Lektion',
    creatorNewLessonDraft: 'Neuer Lektionsentwurf',
    creatorDescriptionFallback: 'Gestalte Skript, Szene, Rendering und Veröffentlichung in einem Creator-Arbeitsbereich.',
    creatorMetadataLabel: 'Creator-Metadaten',
    creatorSummaryLabel: 'Creator-Zusammenfassung',
    creatorNextBestAction: 'Nächster bester Schritt',
    creatorContinueEditing: 'Weiter bearbeiten',
    creatorStatusPublished: 'Veröffentlicht',
    creatorStatusRendering: 'Rendering läuft',
    creatorStatusReady: 'Bereit',
    creatorStatusDraft: 'Entwurf',
    creatorAiReady: 'KI bereit',
    creatorPublishReady: 'Bereit zum Veröffentlichen',
    creatorNeedsAttention: 'Aufmerksamkeit nötig',
    creatorAvatarLabel: 'Avatar',
    creatorVoiceLabel: 'Stimme',
    creatorLanguageLabel: 'Sprache',
    creatorDurationLabel: 'Dauer',
    creatorAutoVoice: 'Automatische Stimme',
    creatorAvatarDisabled: 'Avatar deaktiviert.',
    creatorAvatarProcessing: 'Avatar wird verarbeitet...',
    creatorAvatarFailed: 'Avatar fehlgeschlagen. Das Basisvideo bleibt veröffentlicht.',
    creatorAvatarMotionFallback: 'Avatar-Lippensynchronisation abgeschlossen; Bewegungsfallback verwendet.',
    creatorAvatarStaticFallback: 'Statischer Avatar verwendet, weil die Bewegungsphase fehlgeschlagen ist.',
    creatorAvatarMotionReady: 'Avatar mit Bewegung bereit.',
    creatorAvatarReady: 'Avatar bereit.',
    creatorCreateThisLesson: 'Diese Lektion erstellen',
    creatorAddSourceFile: 'Quelldatei hinzufügen',
    creatorResolveBlocker: 'Blocker lösen',
    creatorRenderUpdatedVideo: 'Aktualisiertes Video rendern',
    creatorSaveCurrentEdits: 'Aktuelle Änderungen speichern',
    creatorPublishReadyLesson: 'Bereite Lektion veröffentlichen',
    creatorWatchPublishedLesson: 'Veröffentlichte Lektion ansehen',
    creatorPreviewDraft: 'Entwurf ansehen',
    creatorDetailCreateLesson: 'Nutze die Entwurfssteuerung, um aus der gewählten Quelle eine Lektion zu erstellen.',
    creatorDetailRenderUpdated: 'Skript-, Folien- oder Stimmänderungen erfordern vor der Veröffentlichung ein neues Rendering.',
    creatorDetailSaveChanges: 'Speichere Entwurfsänderungen vor Rendering oder Veröffentlichung.',
    creatorDetailPublishReady: 'Rendering und Moderation sind bereit für die Veröffentlichung.',
    creatorDetailWatchPublished: 'Die öffentliche Lektion ist live und in Watch zur Prüfung bereit.',
    creatorDetailPreviewDraft: 'Ein gerenderter Entwurf ist für die Vorschau verfügbar.',
    creatorDetailContinueEditing: 'Arbeite im Canvas, bis die Lektion zum Rendern bereit ist.',
    creatorCreating: 'Wird erstellt...',
    creatorCreateLesson: 'Lektion erstellen',
    creatorSaveLocalDraft: 'Lokalen Entwurf speichern',
    creatorRender: 'Rendern',
    creatorRenderRerenderTitle: 'Änderungen speichern und ein neues Video-Rendering einreihen.',
    creatorSaveChanges: 'Änderungen speichern',
    creatorPublish: 'Veröffentlichen',
    creatorWatch: 'Ansehen',
    creatorPreviewInWatch: 'In Watch ansehen',
  },
  it: {
    renderStatus: 'Stato rendering',
    renderReady: 'Pronto',
    renderProcessing: 'In elaborazione',
    renderQueued: 'In coda',
    renderFailed: 'Non riuscito',
    renderDraft: 'Non renderizzato',
    renderIdleHint: "L'attività di rendering apparirà qui.",
    renderActiveHint: 'Puoi continuare a modificare mentre il rendering procede.',
    renderReadyHint: "L'ultimo video è pronto per l'anteprima.",
    renderFailedHint: "Controlla l'errore e riprova il rendering.",
    saving: 'Salvataggio...',
    lastSaved: 'Ultimo salvataggio',
    creatorEyebrow: 'Area creator IA',
    creatorUntitledLesson: 'Lezione senza titolo',
    creatorNewLessonDraft: 'Nuova bozza di lezione',
    creatorDescriptionFallback: 'Modella script, scena, rendering e pubblicazione da un unico spazio creator.',
    creatorMetadataLabel: 'Metadati creator',
    creatorSummaryLabel: 'Riepilogo creator',
    creatorNextBestAction: 'Prossima azione migliore',
    creatorContinueEditing: 'Continua a modificare',
    creatorStatusPublished: 'Pubblicato',
    creatorStatusRendering: 'Rendering',
    creatorStatusReady: 'Pronto',
    creatorStatusDraft: 'Bozza',
    creatorAiReady: 'IA pronta',
    creatorPublishReady: 'Pronto per pubblicare',
    creatorNeedsAttention: 'Richiede attenzione',
    creatorAvatarLabel: 'Avatar',
    creatorVoiceLabel: 'Voce',
    creatorLanguageLabel: 'Lingua',
    creatorDurationLabel: 'Durata',
    creatorAutoVoice: 'Voce automatica',
    creatorAvatarDisabled: 'Avatar disattivato.',
    creatorAvatarProcessing: 'Avatar in elaborazione...',
    creatorAvatarFailed: 'Avatar non riuscito. Il video base resta pubblicato.',
    creatorAvatarMotionFallback: 'Lip-sync avatar completato; usato fallback di movimento.',
    creatorAvatarStaticFallback: 'Avatar statico usato perché la fase di movimento non è riuscita.',
    creatorAvatarMotionReady: 'Avatar pronto con movimento.',
    creatorAvatarReady: 'Avatar pronto.',
    creatorCreateThisLesson: 'Crea questa lezione',
    creatorAddSourceFile: 'Aggiungi file sorgente',
    creatorResolveBlocker: 'Risolvi il blocco',
    creatorRenderUpdatedVideo: 'Renderizza il video aggiornato',
    creatorSaveCurrentEdits: 'Salva modifiche correnti',
    creatorPublishReadyLesson: 'Pubblica la lezione pronta',
    creatorWatchPublishedLesson: 'Guarda la lezione pubblicata',
    creatorPreviewDraft: 'Anteprima bozza',
    creatorDetailCreateLesson: 'Usa i controlli bozza per creare una lezione dalla fonte selezionata.',
    creatorDetailRenderUpdated: 'Le modifiche a script, slide o voce richiedono un nuovo rendering prima della pubblicazione.',
    creatorDetailSaveChanges: 'Salva le modifiche della bozza prima di renderizzare o pubblicare.',
    creatorDetailPublishReady: 'Rendering e moderazione sono pronti per la pubblicazione.',
    creatorDetailWatchPublished: 'La lezione pubblica è online e pronta da rivedere in Watch.',
    creatorDetailPreviewDraft: "È disponibile una bozza renderizzata per l'anteprima del proprietario.",
    creatorDetailContinueEditing: 'Lavora nel canvas finché la lezione è pronta per il rendering.',
    creatorCreating: 'Creazione...',
    creatorCreateLesson: 'Crea lezione',
    creatorSaveLocalDraft: 'Salva bozza locale',
    creatorRender: 'Renderizza',
    creatorRenderRerenderTitle: 'Salva le modifiche e metti in coda un nuovo rendering video.',
    creatorSaveChanges: 'Salva modifiche',
    creatorPublish: 'Pubblica',
    creatorWatch: 'Guarda',
    creatorPreviewInWatch: 'Anteprima in Watch',
  },
  pt: {
    renderStatus: 'Status da renderização',
    renderReady: 'Pronto',
    renderProcessing: 'Processando',
    renderQueued: 'Na fila',
    renderFailed: 'Falhou',
    renderDraft: 'Não renderizado',
    renderIdleHint: 'A atividade de renderização aparecerá aqui.',
    renderActiveHint: 'Você pode continuar editando enquanto a renderização avança.',
    renderReadyHint: 'O vídeo mais recente está pronto para prévia.',
    renderFailedHint: 'Revise o erro e tente renderizar novamente.',
    saving: 'Salvando...',
    lastSaved: 'Último salvamento',
    creatorEyebrow: 'Espaço de criação com IA',
    creatorUntitledLesson: 'Aula sem título',
    creatorNewLessonDraft: 'Novo rascunho de aula',
    creatorDescriptionFallback: 'Ajuste roteiro, cena, renderização e publicação em um só espaço de criação.',
    creatorMetadataLabel: 'Metadados do criador',
    creatorSummaryLabel: 'Resumo do criador',
    creatorNextBestAction: 'Próxima melhor ação',
    creatorContinueEditing: 'Continuar editando',
    creatorStatusPublished: 'Publicado',
    creatorStatusRendering: 'Renderizando',
    creatorStatusReady: 'Pronto',
    creatorStatusDraft: 'Rascunho',
    creatorAiReady: 'IA pronta',
    creatorPublishReady: 'Pronto para publicar',
    creatorNeedsAttention: 'Precisa de atenção',
    creatorAvatarLabel: 'Avatar',
    creatorVoiceLabel: 'Voz',
    creatorLanguageLabel: 'Idioma',
    creatorDurationLabel: 'Duração',
    creatorAutoVoice: 'Voz automática',
    creatorAvatarDisabled: 'Avatar desativado.',
    creatorAvatarProcessing: 'Processando avatar...',
    creatorAvatarFailed: 'Avatar falhou. O vídeo base continua publicado.',
    creatorAvatarMotionFallback: 'Sincronização labial concluída; fallback de movimento usado.',
    creatorAvatarStaticFallback: 'Avatar estático usado porque a etapa de movimento falhou.',
    creatorAvatarMotionReady: 'Avatar pronto com movimento.',
    creatorAvatarReady: 'Avatar pronto.',
    creatorCreateThisLesson: 'Criar esta aula',
    creatorAddSourceFile: 'Adicionar arquivo fonte',
    creatorResolveBlocker: 'Resolver bloqueio',
    creatorRenderUpdatedVideo: 'Renderizar vídeo atualizado',
    creatorSaveCurrentEdits: 'Salvar edições atuais',
    creatorPublishReadyLesson: 'Publicar aula pronta',
    creatorWatchPublishedLesson: 'Assistir aula publicada',
    creatorPreviewDraft: 'Prévia do rascunho',
    creatorDetailCreateLesson: 'Use os controles de rascunho para criar uma aula a partir da fonte selecionada.',
    creatorDetailRenderUpdated: 'Mudanças no roteiro, slide ou voz exigem nova renderização antes da publicação.',
    creatorDetailSaveChanges: 'Salve as mudanças do rascunho antes de renderizar ou publicar.',
    creatorDetailPublishReady: 'Renderização e moderação estão prontas para publicação.',
    creatorDetailWatchPublished: 'A aula pública está no ar e pronta para revisão no Watch.',
    creatorDetailPreviewDraft: 'Um rascunho renderizado está disponível para prévia do proprietário.',
    creatorDetailContinueEditing: 'Trabalhe na tela até a aula estar pronta para renderizar.',
    creatorCreating: 'Criando...',
    creatorCreateLesson: 'Criar aula',
    creatorSaveLocalDraft: 'Salvar rascunho local',
    creatorRender: 'Renderizar',
    creatorRenderRerenderTitle: 'Salve as mudanças e coloque uma nova renderização de vídeo na fila.',
    creatorSaveChanges: 'Salvar alterações',
    creatorPublish: 'Publicar',
    creatorWatch: 'Assistir',
    creatorPreviewInWatch: 'Prévia no Watch',
  },
  ru: {
    renderStatus: 'Статус рендера',
    renderReady: 'Готово',
    renderProcessing: 'Обработка',
    renderQueued: 'В очереди',
    renderFailed: 'Ошибка',
    renderDraft: 'Не отрендерено',
    renderIdleHint: 'Активность рендера появится здесь.',
    renderActiveHint: 'Можно продолжать редактирование, пока идет рендер.',
    renderReadyHint: 'Последнее видео готово к предпросмотру.',
    renderFailedHint: 'Проверьте ошибку и запустите рендер снова.',
    saving: 'Сохранение...',
    lastSaved: 'Последнее сохранение',
    creatorEyebrow: 'Рабочая область AI-создателя',
    creatorUntitledLesson: 'Урок без названия',
    creatorNewLessonDraft: 'Новый черновик урока',
    creatorDescriptionFallback: 'Настраивайте сценарий, сцену, рендер и публикацию в единой рабочей области.',
    creatorMetadataLabel: 'Метаданные создателя',
    creatorSummaryLabel: 'Сводка создателя',
    creatorNextBestAction: 'Следующее лучшее действие',
    creatorContinueEditing: 'Продолжить редактирование',
    creatorStatusPublished: 'Опубликовано',
    creatorStatusRendering: 'Рендеринг',
    creatorStatusReady: 'Готово',
    creatorStatusDraft: 'Черновик',
    creatorAiReady: 'AI готов',
    creatorPublishReady: 'Готово к публикации',
    creatorNeedsAttention: 'Требует внимания',
    creatorAvatarLabel: 'Аватар',
    creatorVoiceLabel: 'Голос',
    creatorLanguageLabel: 'Язык',
    creatorDurationLabel: 'Длительность',
    creatorAutoVoice: 'Автоматический голос',
    creatorAvatarDisabled: 'Аватар отключен.',
    creatorAvatarProcessing: 'Аватар обрабатывается...',
    creatorAvatarFailed: 'Аватар не создан. Базовое видео остается опубликованным.',
    creatorAvatarMotionFallback: 'Синхронизация губ завершена; использован резервный вариант движения.',
    creatorAvatarStaticFallback: 'Использован статичный аватар, потому что этап движения не удался.',
    creatorAvatarMotionReady: 'Аватар готов с движением.',
    creatorAvatarReady: 'Аватар готов.',
    creatorCreateThisLesson: 'Создать этот урок',
    creatorAddSourceFile: 'Добавить исходный файл',
    creatorResolveBlocker: 'Устранить блокировку',
    creatorRenderUpdatedVideo: 'Отрендерить обновленное видео',
    creatorSaveCurrentEdits: 'Сохранить правки',
    creatorPublishReadyLesson: 'Опубликовать готовый урок',
    creatorWatchPublishedLesson: 'Смотреть опубликованный урок',
    creatorPreviewDraft: 'Предпросмотр черновика',
    creatorDetailCreateLesson: 'Используйте элементы черновика, чтобы создать урок из выбранного источника.',
    creatorDetailRenderUpdated: 'Изменения сценария, слайда или голоса требуют нового рендера перед публикацией.',
    creatorDetailSaveChanges: 'Сохраните изменения черновика перед рендером или публикацией.',
    creatorDetailPublishReady: 'Рендер и модерация готовы к публикации.',
    creatorDetailWatchPublished: 'Публичный урок опубликован и готов к проверке в Watch.',
    creatorDetailPreviewDraft: 'Отрендеренный черновик доступен для предпросмотра владельцем.',
    creatorDetailContinueEditing: 'Работайте на холсте, пока урок не будет готов к рендеру.',
    creatorCreating: 'Создание...',
    creatorCreateLesson: 'Создать урок',
    creatorSaveLocalDraft: 'Сохранить локальный черновик',
    creatorRender: 'Рендер',
    creatorRenderRerenderTitle: 'Сохранить изменения и поставить новый рендер видео в очередь.',
    creatorSaveChanges: 'Сохранить изменения',
    creatorPublish: 'Опубликовать',
    creatorWatch: 'Смотреть',
    creatorPreviewInWatch: 'Предпросмотр в Watch',
  },
  ja: {
    renderStatus: 'レンダー状況',
    renderReady: '準備完了',
    renderProcessing: '処理中',
    renderQueued: 'キュー待ち',
    renderFailed: '失敗',
    renderDraft: '未レンダー',
    renderIdleHint: 'レンダー状況はここに表示されます。',
    renderActiveHint: 'レンダー中も編集を続けられます。',
    renderReadyHint: '最新の動画をプレビューできます。',
    renderFailedHint: 'エラーを確認して、もう一度レンダーしてください。',
    saving: '保存中...',
    lastSaved: '最終保存',
    creatorEyebrow: 'AIクリエイター ワークスペース',
    creatorUntitledLesson: '無題のレッスン',
    creatorNewLessonDraft: '新しいレッスン下書き',
    creatorDescriptionFallback: '台本、シーン、レンダー、公開までを1つの制作スペースで整えます。',
    creatorMetadataLabel: 'クリエイター メタデータ',
    creatorSummaryLabel: 'クリエイター概要',
    creatorNextBestAction: '次に行うこと',
    creatorContinueEditing: '編集を続ける',
    creatorStatusPublished: '公開済み',
    creatorStatusRendering: 'レンダー中',
    creatorStatusReady: '準備完了',
    creatorStatusDraft: '下書き',
    creatorAiReady: 'AI準備完了',
    creatorPublishReady: '公開準備完了',
    creatorNeedsAttention: '確認が必要',
    creatorAvatarLabel: 'アバター',
    creatorVoiceLabel: '音声',
    creatorLanguageLabel: '言語',
    creatorDurationLabel: '長さ',
    creatorAutoVoice: '自動音声',
    creatorAvatarDisabled: 'アバターは無効です。',
    creatorAvatarProcessing: 'アバターを処理中...',
    creatorAvatarFailed: 'アバターに失敗しました。ベース動画は公開されたままです。',
    creatorAvatarMotionFallback: 'アバターのリップシンクが完了しました。モーションの代替が使われました。',
    creatorAvatarStaticFallback: 'モーション工程に失敗したため、静止アバターが使われました。',
    creatorAvatarMotionReady: 'アバターはモーション付きで準備完了です。',
    creatorAvatarReady: 'アバター準備完了。',
    creatorCreateThisLesson: 'このレッスンを作成',
    creatorAddSourceFile: 'ソースファイルを追加',
    creatorResolveBlocker: 'ブロックを解消',
    creatorRenderUpdatedVideo: '更新動画をレンダー',
    creatorSaveCurrentEdits: '現在の編集を保存',
    creatorPublishReadyLesson: '準備済みレッスンを公開',
    creatorWatchPublishedLesson: '公開済みレッスンを見る',
    creatorPreviewDraft: '下書きをプレビュー',
    creatorDetailCreateLesson: '選択したソースからレッスンを作成するには、下書きコントロールを使います。',
    creatorDetailRenderUpdated: '台本、スライド、音声の変更は、公開前に新しいレンダーが必要です。',
    creatorDetailSaveChanges: 'レンダーまたは公開の前に下書きの変更を保存してください。',
    creatorDetailPublishReady: 'レンダーとモデレーションは公開準備ができています。',
    creatorDetailWatchPublished: '公開レッスンはライブで、Watchで確認できます。',
    creatorDetailPreviewDraft: 'レンダー済み下書きを所有者プレビューで確認できます。',
    creatorDetailContinueEditing: 'レッスンがレンダー準備完了になるまでキャンバスで作業します。',
    creatorCreating: '作成中...',
    creatorCreateLesson: 'レッスンを作成',
    creatorSaveLocalDraft: 'ローカル下書きを保存',
    creatorRender: 'レンダー',
    creatorRenderRerenderTitle: '変更を保存し、動画の再レンダーをキューに追加します。',
    creatorSaveChanges: '変更を保存',
    creatorPublish: '公開',
    creatorWatch: '見る',
    creatorPreviewInWatch: 'Watchでプレビュー',
  },
  ko: {
    renderStatus: '렌더 상태',
    renderReady: '준비됨',
    renderProcessing: '처리 중',
    renderQueued: '대기 중',
    renderFailed: '실패',
    renderDraft: '렌더되지 않음',
    renderIdleHint: '렌더 활동이 여기에 표시됩니다.',
    renderActiveHint: '렌더가 진행되는 동안 계속 편집할 수 있습니다.',
    renderReadyHint: '최신 비디오를 미리 볼 수 있습니다.',
    renderFailedHint: '오류를 확인하고 다시 렌더링하세요.',
    saving: '저장 중...',
    lastSaved: '마지막 저장',
    creatorEyebrow: 'AI 크리에이터 작업 공간',
    creatorUntitledLesson: '제목 없는 레슨',
    creatorNewLessonDraft: '새 레슨 초안',
    creatorDescriptionFallback: '스크립트, 장면, 렌더링, 게시 흐름을 하나의 제작 공간에서 다듬습니다.',
    creatorMetadataLabel: '크리에이터 메타데이터',
    creatorSummaryLabel: '크리에이터 요약',
    creatorNextBestAction: '다음 최적 작업',
    creatorContinueEditing: '계속 편집',
    creatorStatusPublished: '게시됨',
    creatorStatusRendering: '렌더링 중',
    creatorStatusReady: '준비됨',
    creatorStatusDraft: '초안',
    creatorAiReady: 'AI 준비됨',
    creatorPublishReady: '게시 준비됨',
    creatorNeedsAttention: '확인 필요',
    creatorAvatarLabel: '아바타',
    creatorVoiceLabel: '음성',
    creatorLanguageLabel: '언어',
    creatorDurationLabel: '길이',
    creatorAutoVoice: '자동 음성',
    creatorAvatarDisabled: '아바타가 비활성화되었습니다.',
    creatorAvatarProcessing: '아바타 처리 중...',
    creatorAvatarFailed: '아바타에 실패했습니다. 기본 비디오는 계속 게시됩니다.',
    creatorAvatarMotionFallback: '아바타 립싱크가 완료되었습니다. 모션 대체가 사용되었습니다.',
    creatorAvatarStaticFallback: '모션 단계 실패로 정적 아바타가 사용되었습니다.',
    creatorAvatarMotionReady: '아바타가 모션과 함께 준비되었습니다.',
    creatorAvatarReady: '아바타 준비됨.',
    creatorCreateThisLesson: '이 레슨 만들기',
    creatorAddSourceFile: '소스 파일 추가',
    creatorResolveBlocker: '차단 요소 해결',
    creatorRenderUpdatedVideo: '업데이트된 비디오 렌더링',
    creatorSaveCurrentEdits: '현재 편집 저장',
    creatorPublishReadyLesson: '준비된 레슨 게시',
    creatorWatchPublishedLesson: '게시된 레슨 보기',
    creatorPreviewDraft: '초안 미리보기',
    creatorDetailCreateLesson: '선택한 소스에서 레슨을 만들려면 초안 컨트롤을 사용하세요.',
    creatorDetailRenderUpdated: '스크립트, 슬라이드 또는 음성 변경은 게시 전에 새 렌더가 필요합니다.',
    creatorDetailSaveChanges: '렌더링 또는 게시 전에 초안 변경 사항을 저장하세요.',
    creatorDetailPublishReady: '렌더링과 검토가 게시 준비를 마쳤습니다.',
    creatorDetailWatchPublished: '공개 레슨이 라이브 상태이며 Watch에서 검토할 수 있습니다.',
    creatorDetailPreviewDraft: '렌더링된 초안을 소유자 미리보기로 볼 수 있습니다.',
    creatorDetailContinueEditing: '레슨이 렌더링 준비가 될 때까지 캔버스에서 작업하세요.',
    creatorCreating: '생성 중...',
    creatorCreateLesson: '레슨 만들기',
    creatorSaveLocalDraft: '로컬 초안 저장',
    creatorRender: '렌더링',
    creatorRenderRerenderTitle: '변경 사항을 저장하고 비디오 재렌더를 대기열에 추가합니다.',
    creatorSaveChanges: '변경 저장',
    creatorPublish: '게시',
    creatorWatch: '보기',
    creatorPreviewInWatch: 'Watch에서 미리보기',
  },
  zh: {
    renderStatus: '渲染状态',
    renderReady: '就绪',
    renderProcessing: '处理中',
    renderQueued: '排队中',
    renderFailed: '失败',
    renderDraft: '未渲染',
    renderIdleHint: '渲染活动会显示在这里。',
    renderActiveHint: '渲染继续时你仍可编辑。',
    renderReadyHint: '最新视频已可预览。',
    renderFailedHint: '请检查错误并重新渲染。',
    saving: '正在保存...',
    lastSaved: '上次保存',
    creatorEyebrow: 'AI 创作者工作区',
    creatorUntitledLesson: '未命名课程',
    creatorNewLessonDraft: '新课程草稿',
    creatorDescriptionFallback: '在一个创作空间中完成脚本、场景、渲染和发布流程。',
    creatorMetadataLabel: '创作者元数据',
    creatorSummaryLabel: '创作者摘要',
    creatorNextBestAction: '下一步最佳操作',
    creatorContinueEditing: '继续编辑',
    creatorStatusPublished: '已发布',
    creatorStatusRendering: '渲染中',
    creatorStatusReady: '就绪',
    creatorStatusDraft: '草稿',
    creatorAiReady: 'AI 就绪',
    creatorPublishReady: '可发布',
    creatorNeedsAttention: '需要关注',
    creatorAvatarLabel: '头像',
    creatorVoiceLabel: '语音',
    creatorLanguageLabel: '语言',
    creatorDurationLabel: '时长',
    creatorAutoVoice: '自动语音',
    creatorAvatarDisabled: '头像已停用。',
    creatorAvatarProcessing: '正在处理头像...',
    creatorAvatarFailed: '头像失败。基础视频仍保持发布。',
    creatorAvatarMotionFallback: '头像口型同步已完成；已使用动作备用方案。',
    creatorAvatarStaticFallback: '动作阶段失败，已使用静态头像备用方案。',
    creatorAvatarMotionReady: '头像已带动作就绪。',
    creatorAvatarReady: '头像已就绪。',
    creatorCreateThisLesson: '创建此课程',
    creatorAddSourceFile: '添加源文件',
    creatorResolveBlocker: '解决阻碍',
    creatorRenderUpdatedVideo: '渲染更新后的视频',
    creatorSaveCurrentEdits: '保存当前编辑',
    creatorPublishReadyLesson: '发布已就绪课程',
    creatorWatchPublishedLesson: '观看已发布课程',
    creatorPreviewDraft: '预览草稿',
    creatorDetailCreateLesson: '使用草稿控件从所选源文件创建课程。',
    creatorDetailRenderUpdated: '脚本、幻灯片或语音更改需要在发布前重新渲染。',
    creatorDetailSaveChanges: '请在渲染或发布前保存草稿更改。',
    creatorDetailPublishReady: '渲染和审核已准备好发布。',
    creatorDetailWatchPublished: '公开课程已上线，可在 Watch 中复核。',
    creatorDetailPreviewDraft: '已渲染草稿可供所有者预览。',
    creatorDetailContinueEditing: '在画布中继续工作，直到课程可渲染。',
    creatorCreating: '正在创建...',
    creatorCreateLesson: '创建课程',
    creatorSaveLocalDraft: '保存本地草稿',
    creatorRender: '渲染',
    creatorRenderRerenderTitle: '保存更改并将视频重新渲染加入队列。',
    creatorSaveChanges: '保存更改',
    creatorPublish: '发布',
    creatorWatch: '观看',
    creatorPreviewInWatch: '在 Watch 中预览',
  },
  ar: {
    renderStatus: 'حالة التصيير',
    renderReady: 'جاهز',
    renderProcessing: 'قيد المعالجة',
    renderQueued: 'في قائمة الانتظار',
    renderFailed: 'فشل',
    renderDraft: 'غير مصير',
    renderIdleHint: 'سيظهر نشاط التصيير هنا.',
    renderActiveHint: 'يمكنك متابعة التحرير أثناء استمرار التصيير.',
    renderReadyHint: 'أحدث فيديو جاهز للمعاينة.',
    renderFailedHint: 'راجع الخطأ وحاول التصيير مرة أخرى.',
    saving: 'جار الحفظ...',
    lastSaved: 'آخر حفظ',
    creatorEyebrow: 'مساحة منشئ بالذكاء الاصطناعي',
    creatorUntitledLesson: 'درس بلا عنوان',
    creatorNewLessonDraft: 'مسودة درس جديدة',
    creatorDescriptionFallback: 'صمم النص والمشهد والتصيير والنشر من مساحة إنشاء واحدة.',
    creatorMetadataLabel: 'بيانات المنشئ',
    creatorSummaryLabel: 'ملخص المنشئ',
    creatorNextBestAction: 'أفضل خطوة تالية',
    creatorContinueEditing: 'متابعة التحرير',
    creatorStatusPublished: 'منشور',
    creatorStatusRendering: 'جار التصيير',
    creatorStatusReady: 'جاهز',
    creatorStatusDraft: 'مسودة',
    creatorAiReady: 'الذكاء الاصطناعي جاهز',
    creatorPublishReady: 'جاهز للنشر',
    creatorNeedsAttention: 'يتطلب الانتباه',
    creatorAvatarLabel: 'الأفاتار',
    creatorVoiceLabel: 'الصوت',
    creatorLanguageLabel: 'اللغة',
    creatorDurationLabel: 'المدة',
    creatorAutoVoice: 'صوت تلقائي',
    creatorAvatarDisabled: 'الأفاتار معطل.',
    creatorAvatarProcessing: 'جار معالجة الأفاتار...',
    creatorAvatarFailed: 'فشل الأفاتار. يبقى الفيديو الأساسي منشورا.',
    creatorAvatarMotionFallback: 'اكتملت مزامنة شفاه الأفاتار؛ تم استخدام حركة بديلة.',
    creatorAvatarStaticFallback: 'تم استخدام أفاتار ثابت لأن مرحلة الحركة فشلت.',
    creatorAvatarMotionReady: 'الأفاتار جاهز مع الحركة.',
    creatorAvatarReady: 'الأفاتار جاهز.',
    creatorCreateThisLesson: 'إنشاء هذا الدرس',
    creatorAddSourceFile: 'إضافة ملف مصدر',
    creatorResolveBlocker: 'حل العائق',
    creatorRenderUpdatedVideo: 'تصيير الفيديو المحدث',
    creatorSaveCurrentEdits: 'حفظ التحريرات الحالية',
    creatorPublishReadyLesson: 'نشر الدرس الجاهز',
    creatorWatchPublishedLesson: 'مشاهدة الدرس المنشور',
    creatorPreviewDraft: 'معاينة المسودة',
    creatorDetailCreateLesson: 'استخدم عناصر تحكم المسودة لإنشاء درس من المصدر المحدد.',
    creatorDetailRenderUpdated: 'تتطلب تغييرات النص أو الشريحة أو الصوت تصييرا جديدا قبل النشر.',
    creatorDetailSaveChanges: 'احفظ تغييرات المسودة قبل التصيير أو النشر.',
    creatorDetailPublishReady: 'التصيير والمراجعة جاهزان للنشر.',
    creatorDetailWatchPublished: 'الدرس العام مباشر وجاهز للمراجعة في Watch.',
    creatorDetailPreviewDraft: 'تتوفر مسودة مصيرة لمعاينة المالك.',
    creatorDetailContinueEditing: 'اعمل في اللوحة حتى يصبح الدرس جاهزا للتصيير.',
    creatorCreating: 'جار الإنشاء...',
    creatorCreateLesson: 'إنشاء درس',
    creatorSaveLocalDraft: 'حفظ المسودة المحلية',
    creatorRender: 'تصيير',
    creatorRenderRerenderTitle: 'احفظ التغييرات وأضف إعادة تصيير الفيديو إلى قائمة الانتظار.',
    creatorSaveChanges: 'حفظ التغييرات',
    creatorPublish: 'نشر',
    creatorWatch: 'مشاهدة',
    creatorPreviewInWatch: 'معاينة في Watch',
  },
};

export function studioWorkspaceLocale(rawLocale = '') {
  const baseLocale = String(rawLocale || '').trim().toLowerCase().split(/[-_]/)[0];
  return Object.prototype.hasOwnProperty.call(STUDIO_WORKSPACE_MESSAGES, baseLocale) ? baseLocale : 'en';
}

export function studioWorkspaceCopy(rawLocale = '') {
  const locale = studioWorkspaceLocale(rawLocale);
  return {
    ...STUDIO_WORKSPACE_MESSAGES.en,
    ...STUDIO_WORKSPACE_MESSAGES[locale],
  };
}
