# Generated by Django 4.2.29 on 2026-03-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_progress_srt_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceprofile',
            name='provider',
            field=models.CharField(choices=[('xtts_v2', 'XTTS v2 (Coqui, default)'), ('gtts', 'gTTS (Google, fallback)'), ('openai', 'OpenAI'), ('elevenlabs', 'ElevenLabs')], default='xtts_v2', max_length=50),
        ),
    ]
