# Generated by ChatGPT on 2026-04-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_category_project_is_published_lessoncomment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                ("source_slide_index", models.PositiveIntegerField(default=0)),
                ("split_index", models.PositiveIntegerField(default=0)),
                ("page_key", models.CharField(max_length=64)),
                ("original_text", models.TextField(blank=True)),
                ("narration_text", models.TextField(blank=True)),
                ("rich_text_html", models.TextField(blank=True)),
                ("subtitle_chunks", models.JSONField(blank=True, default=list)),
                ("chunk_timeline", models.JSONField(blank=True, default=list)),
                ("whiteboard_mode", models.BooleanField(default=False)),
                ("start_seconds", models.FloatField(blank=True, null=True)),
                ("end_seconds", models.FloatField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transcript_pages", to="core.project"),
                ),
            ],
            options={
                "ordering": ["project", "order"],
                "unique_together": {("project", "page_key")},
            },
        ),
    ]
