# Generated by ChatGPT on 2026-04-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_transcriptpage_and_project_editor_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptpage",
            name="editor_document",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
