# Generated by Django 4.2.29 on 2026-05-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_publisher_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_moderation_run_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='moderation_status',
            field=models.CharField(choices=[('not_scanned', 'Not scanned'), ('pending', 'Pending'), ('approved', 'Approved'), ('revision_required', 'Revision required'), ('needs_admin_review', 'Needs admin review'), ('admin_approved', 'Admin approved'), ('admin_rejected', 'Admin rejected'), ('failed', 'Failed')], db_index=True, default='not_scanned', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='moderation_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
