# Generated by Django 4.2.29 on 2026-05-08 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_userprofile_avatar_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_publishers', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='publisherfollow',
            constraint=models.CheckConstraint(check=models.Q(('follower_id', models.F('publisher_id')), _negated=True), name='publisherfollow_no_self_follow'),
        ),
        migrations.AlterUniqueTogether(
            name='publisherfollow',
            unique_together={('follower', 'publisher')},
        ),
    ]
