# Generated by Django 4.2.29 on 2026-05-08 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_playlist_playlistitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='core.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_savedp_user_id_b7f447_idx'), models.Index(fields=['playlist', 'created_at'], name='core_savedp_playlis_de437b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='savedplaylist',
            constraint=models.UniqueConstraint(fields=('user', 'playlist'), name='unique_saved_playlist'),
        ),
    ]
