# Generated by Django 4.2.29 on 2026-05-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_savedplaylist_savedplaylist_unique_saved_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='draft_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
