# Generated by Django 4.2.29 on 2026-05-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_project_avatar_processing_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHelpContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('body', models.TextField()),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=80)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_address', models.TextField(blank=True)),
                ('support_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site help content',
                'verbose_name_plural': 'site help content',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
