# Generated by Django 4.2.29 on 2026-05-17 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_sitehelpcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('student_followed_publisher_new_lesson', 'Followed publisher posted a new lesson'), ('publisher_comment_on_lesson', 'Someone commented on my lesson'), ('publisher_lesson_render_done', 'Lesson render completed'), ('publisher_lesson_render_failed', 'Lesson render failed'), ('publisher_avatar_render_done', 'Avatar render completed'), ('publisher_avatar_render_failed', 'Avatar render failed')], db_index=True, max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.job')),
                ('lesson_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.lessoncomment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.project')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_user', 'is_read', 'created_at'], name='core_notifi_recipie_6ae03c_idx'), models.Index(fields=['recipient_user', 'created_at'], name='core_notifi_recipie_883408_idx'), models.Index(fields=['event_type', 'created_at'], name='core_notifi_event_t_c8a797_idx')],
            },
        ),
    ]
