# Generated by Django 4.2.29 on 2026-05-18 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_merge_publisher_profile_scalability_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonIntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('provider', models.CharField(default='heuristic', max_length=40)),
                ('provider_chain', models.JSONField(blank=True, default=list)),
                ('fallback_used', models.BooleanField(default=False)),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('summary', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('complexity_level', models.CharField(blank=True, max_length=20)),
                ('complexity_score', models.PositiveSmallIntegerField(default=0)),
                ('complexity_reasons', models.JSONField(blank=True, default=list)),
                ('clarity_warnings', models.JSONField(blank=True, default=list)),
                ('page_suggestions', models.JSONField(blank=True, default=list)),
                ('expanded_narration_suggestions', models.JSONField(blank=True, default=list)),
                ('suggested_tags', models.JSONField(blank=True, default=list)),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_intelligence_reports', to='core.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_intelligence_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='c_lir_project_created_idx'), models.Index(fields=['project', 'source_hash'], name='c_lir_project_hash_idx')],
            },
        ),
    ]
