# Generated by Django 4.2.29 on 2026-05-18 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0029_lesson_intelligence_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsIntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(db_index=True, default='creator', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('provider', models.CharField(default='heuristic', max_length=40)),
                ('provider_chain', models.JSONField(blank=True, default=list)),
                ('fallback_used', models.BooleanField(default=False)),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('date_range', models.JSONField(blank=True, default=dict)),
                ('category_filter', models.CharField(blank=True, max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('health_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('insights', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('lesson_actions', models.JSONField(blank=True, default=list)),
                ('category_actions', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_intelligence_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['requested_by', '-created_at'], name='c_air_user_created_idx'), models.Index(fields=['requested_by', 'scope', 'source_hash'], name='c_air_user_scope_hash_idx'), models.Index(fields=['scope', '-created_at'], name='c_air_scope_created_idx')],
            },
        ),
    ]
