# Generated by Django 4.2.29 on 2026-05-22 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0030_analyticsintelligencereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latest_publisher_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='latest_review_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='manual_moderation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='manual_moderation_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_moderation_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='manual_moderation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='manual_moderation_status',
            field=models.CharField(blank=True, choices=[('', 'No manual decision'), ('approved', 'Approved'), ('blocked', 'Blocked'), ('rejected', 'Rejected'), ('request_changes', 'Request changes'), ('needs_review', 'Needs review')], db_index=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='moderation_blocked_until_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('student_followed_publisher_new_lesson', 'Followed publisher posted a new lesson'), ('publisher_comment_on_lesson', 'Someone commented on my lesson'), ('publisher_lesson_render_done', 'Lesson render completed'), ('publisher_lesson_render_failed', 'Lesson render failed'), ('publisher_avatar_render_done', 'Avatar render completed'), ('publisher_avatar_render_failed', 'Avatar render failed'), ('publisher_lesson_moderation_action', 'Lesson moderation action')], db_index=True, max_length=80),
        ),
    ]
