# Generated by Django 4.2.30 on 2026-05-29 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0031_project_latest_publisher_change_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderFollowUpIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('targeted', 'Targeted'), ('full', 'Full')], default='targeted', max_length=20)),
                ('page_keys', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('dispatched', 'Dispatched'), ('cleared', 'Cleared'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_followup_intents', to='core.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_followup_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='c_rfi_project_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='renderfollowupintent',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'claimed', 'dispatched'])), fields=('project',), name='uniq_active_render_followup_intent'),
        ),
    ]
